title:My awosome tittle
author: Tim0201
email: your-email@domain.com
# social links
twitter_username: sorry,i haven twitter 
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme:minima
